### ISSUE TITLE
Jekyll not updating from data files?

### ISSUE THREAD

**Issue by markallenthornton** [computational-san/computational-san.github.io#7]
Despite the fact that Arjen and my labs were already listed in the labs.csv file, they weren't showing up in the affiliated labs page, so I think jekyll may not be doing it's pseudodynamic update thing (I'm not familiar with that system, so can't comment as to the reason).

**Comment by ljchang** [comment]
oh sorry, they need to be merged before website updates, which I didn't do. Fixed now, thanks!
